site_name: OpsPilot Documentation
site_url: https://docs.fusionreactor.io/
repo_name: opspilot
repo_url: https://github.com/intergral/opspilot-docs
edit_uri: edit/main/docs/


theme:
  name: material
  favicon: op-logo-white.png
  logo: Data-insights/Features/images/whiteOP.svg
  features:
    - navigation.sections
    - navigation.footer
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit  # This enables the edit button on each page
  language: en
  font:  
    text: 'Inter'
    code: 'monospace'
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


nav:
  - WELCOME:
     - Get Started: index.md
     - UI Overview: Data-insights/Features/overview.md
  - AI:
     - OpsPilot Assistant:
        - Overview: Data-insights/Features/OpsPilot/AIoverview.md
        - User guide: Data-insights/Features/OpsPilot/OpsPilot-user-guide.md
     - Knowledge: Data-insights/Features/OpsPilot/OpsPilot-Hub/Knowledge.md
     - MCP Interfaces:
        - OpsPilot MCP:
           - Overview: Monitor-your-data/MCP/mcp-overview.md
           - Install: Monitor-your-data/MCP/MCP.md
        - Katie - Kubernetes tooling for AI:
           - Overview: Monitor-your-data/Katie/overview.md
           - Install MCP: Monitor-your-data/Katie/install.md
  - DASHBOARDS:
     - About Dashboards: Data-insights/Features/Dashboards/about-dashboards.md
     - Work with Dashboards:
        - Create a Dashboard: Data-insights/Features/Dashboards/create-dashboard.md
        - Manage Dashboards: Data-insights/Features/Dashboards/manage-dashboards.md
        - Import & Export: Data-insights/Features/Dashboards/import-export.md
     - Work with Panels:
        - Configure Panels: Data-insights/Features/Dashboards/configure-panels.md
        - Build Queries: Data-insights/Features/Dashboards/build-queries.md
        - Add Variables: Data-insights/Features/Dashboards/add-variables.md
  - INTEGRATIONS:
     - Overview: Data-insights/Features/integrations.md
     - Chat:
        - Slack: Data-insights/Features/Integrations/Chat/slack.md
     - SDKs:
        - FusionReactor: Data-insights/Features/Integrations/SDKs/fusionreactor.md
     - Ticketing:
        - Jira: Data-insights/Features/Integrations/Ticketing/jira.md
  - MONITORING:
     - Servers: Data-insights/Features/Explore-servers.md
     - Applications: Data-insights/Features/applications.md
     - Database: Data-insights/Features/database.md
     - Kubernetes:
        - Overview: Monitor-your-data/Kubernetes-monitoring/overview.md
        - Shipping data: Monitor-your-data/Kubernetes-monitoring/Shipping.md
     - Alerting:
        - Overview: Data-insights/Features/Alerting/Alerts-overview.md
        - Rules: Data-insights/Features/Alerting/Alert-Rules/Configure-rules.md
        - Contact Points:
           - Overview: Data-insights/Features/Alerting/Contact-points.md
           - Notification Templates: Data-insights/Features/Alerting/Templates.md
        - Notification Policy:
           - Overview: Data-insights/Features/Alerting/Notifications.md
           - Time intervals: Data-insights/Features/Alerting/Mute-timings.md
        - Silences: Data-insights/Features/Alerting/Silences.md
        - Firing Alerts: Data-insights/Features/Alerting/Active-alerts.md
        - Examples:
           - Overview: Data-insights/Features/alerting-examples.md
           - FR Agent metrics: Data-insights/Features/FR-Agent-Metrics.md
        - Anomaly Detection:
           - Overview: Data-insights/Features/Anomaly-Detection/ADoverview.md
           - User guide: Data-insights/Features/Anomaly-Detection/ADuserguide.md
        - Troubleshooting: Data-insights/Features/Alerting/Troubleshooting.md
        - FAQ: Data-insights/Features/Alerting/FAQ.md
     - Incidents:
        - Overview: Data-insights/Features/Incidents/incidents.md
        - Settings: Data-insights/Features/Incidents/Settings.md
  - TELEMETRY:
     - Logs: Data-insights/Features/explore-logs.md
     - Metrics: Data-insights/Features/explore-metrics.md
     - Traces: Data-insights/Features/explore-traces.md
     - Explore: Data-insights/Features/explore.md
  - DATA COLLECTION:
     - OpenTelemetry:
        - Get started: Monitor-your-data/OpenTelemetry/getting-started.md
        - Instrumentation:
           - Overview: Monitor-your-data/OpenTelemetry/Instrumentation/Overview.md
           - Guides:
              - C++: Monitor-your-data/OpenTelemetry/Instrumentation/Cpp.md
              - .NET: Monitor-your-data/OpenTelemetry/Instrumentation/DotNet.md
              - Erlang/Elixir: Monitor-your-data/OpenTelemetry/Instrumentation/Erlang.md
              - Go: Monitor-your-data/OpenTelemetry/Instrumentation/Go.md
              - Java: Monitor-your-data/OpenTelemetry/Instrumentation/Java.md
              - Kotlin: Monitor-your-data/OpenTelemetry/Instrumentation/Kotlin.md
              - Node.js: Monitor-your-data/OpenTelemetry/Instrumentation/node.md
              - PHP: Monitor-your-data/OpenTelemetry/Instrumentation/PHP.md
              - Python: Monitor-your-data/OpenTelemetry/Instrumentation/Python.md
              - Ruby: Monitor-your-data/OpenTelemetry/Instrumentation/Ruby.md
              - Rust: Monitor-your-data/OpenTelemetry/Instrumentation/Rust.md
              - Swift: Monitor-your-data/OpenTelemetry/Instrumentation/Swift.md
        - Shipping data:
           - Overview: Monitor-your-data/OpenTelemetry/Shipping/overview.md
           - OpenTelemetry Collector: Monitor-your-data/OpenTelemetry/Shipping/Collector.md
           - Grafana Alloy: Monitor-your-data/OpenTelemetry/Shipping/Grafana-agent.md
        - Visualize:
           - Metrics: Monitor-your-data/OpenTelemetry/Visualize/Metrics.md
           - Traces: Monitor-your-data/OpenTelemetry/Visualize/Traces.md
           - Logs: Monitor-your-data/OpenTelemetry/Visualize/Logs.md
           - Distributed tracing: Monitor-your-data/OpenTelemetry/Visualize/Distributed-tracing.md
        - Configuration: Monitor-your-data/OpenTelemetry/Configuration.md
        - FAQ: Monitor-your-data/OpenTelemetry/FAQ.md
        - Troubleshooting: Monitor-your-data/OpenTelemetry/Troubleshooting.md
     - Infrastructure Monitoring:
        - Overview: Monitor-your-data/Infrastructure-monitoring/overview.md
     - Deep:
        - Overview: Monitor-your-data/Deep/overview.md
        - Search: Data-insights/Features/Deep/Search.md
        - Tracepoints: Data-insights/Features/Deep/Create-Tracepoint.md
  - MISCELLANEOUS:
     - What's New: Latest-updates/WhatsNew.md
     - Releases:
        - Overview: Latest-updates/Releases.md
        - OpsPilot: Latest-updates/OpsPilot-releases.md
        - Downloads: Latest-updates/Downloads.md
     - Tutorials & Walkthroughs:
        - Overview: Getting-started/Tutorials/Overview.md
        - New UI FAQ: Getting-started/Tutorials/new-ui-faq.md
        - Performance analysis:
           - Post-crash troubleshooting: Getting-started/Tutorials/crash-troubleshoot-cloud.md
           - Getting-started/Tutorials/resolve-slow-queries.md
           - Getting-started/Troubleshooting/best-ways-to-monitor.md
           - Getting-started/Troubleshooting/ignore-scheduled-tasks.md
           - Getting-started/Troubleshooting/identify-slow-requests.md
           - Getting-started/Tutorials/UEM.md
           - Getting-started/Tutorials/memory-leaks.md
        - Application observability:
           - Get to know the UI: Getting-started/Tutorials/know-the-ui.md
           - Create a dashboard: Getting-started/Tutorials/create-dashboard.md
           - Getting-started/Tutorials/RCA-in-Services.md
           - Getting-started/Troubleshooting/alerts-slow-requests.md
        - Infrastructure observability:
           - Getting-started/Tutorials/scalability.md
           - Getting-started/Troubleshooting/reports.md
           - Getting-started/Troubleshooting/cpu-spikes.md
           - Getting-started/Tutorials/capacity-planning.md
        - Common support issues:
           - Getting-started/Tutorials/Common-issues/find-license-key.md
           - Getting-started/Tutorials/Common-issues/move-license-key.md
           - Getting-started/Tutorials/Common-issues/billing-usage.md
           - Getting-started/Tutorials/Common-issues/increase-SQL-query.md
           - Getting-started/Tutorials/Common-issues/set-email-reports.md
           - Getting-started/Tutorials/Common-issues/check-license-seat.md
           - Getting-started/Tutorials/Common-issues/endpoints.md
           - Getting-started/Tutorials/Common-issues/CF2025-and-FR-2025-Startup-issue.md
           - Getting-started/Tutorials/Common-issues/FR-wmic.exe-error.md
           - Getting-started/Tutorials/Common-issues/TLS-deprecation-guide.md
     - Administration:
        - Usage & Details: Admin-and-data/usage-and-details.md
        - Billing:
           - Overview: Admin-and-data/Billing/Cloud/overview.md
           - FAQ: Admin-and-data/Billing/Cloud/faq.md
        - Invoices: Admin-and-data/invoices.md
        - API Keys: Admin-and-data/api-keys.md
        - Organization Settings: Admin-and-data/organization-settings.md
        - Users:
           - Organization Users: Admin-and-data/Account/Cloud/users.md
           - User Profile: Admin-and-data/Account/Cloud/profile.md
           - User Security: Admin-and-data/Account/Cloud/security.md
        - Data limits: Admin-and-data/Limits.md
        - Security: Admin-and-data/security.md
        - Legal:
           - Terms of Service: Admin-and-data/tos.md
           - EULA: Admin-and-data/EULA.md
           - Third Party Licenses: Admin-and-data/Third-Party-Licenses/licenses.md
     - Contribute:
        - Contribute/how-to-contribute.md
        - Style Guide:
           - Overview: Contribute/style-guide/overview.md
           - Images: Contribute/style-guide/images.md
           - Language & grammar:
              - Abbreviations: Contribute/style-guide/Language-and-grammar/Abbreviations.md
              - Capitalization: Contribute/style-guide/Language-and-grammar/Capitalization.md
              - Contractions: Contribute/style-guide/Language-and-grammar/Contractions.md
              - Formatting: Contribute/style-guide/Language-and-grammar/Formatting.md

plugins:
   - glightbox:
       selector: '.md-content img:not(.no-lightbox)'
   - search
   - redirects:
      redirect_maps:
         'test.md': 'Admin-and-data/Licensing/Licensing.md'
         'fr/help/Licensing.md': 'Admin-and-data/Licensing/Licensing.md'
         'fr/help/Using+a+License+stored+in+the+Instance+Configuration+File.md': 'Admin-and-data/Licensing/Licensing.md'
         'fr/help/Home.md': 'index.md'
         'fr/help/Users.md': 'Admin-and-data/Account/Cloud/users.md'
         'fr/help/Unsupported+Configurations.md': 'index.md'
         'fr/help/Corrupt+Configurations.md': 'index.md'
         'fr/help/Locked.md': 'index.md'
         'fr/help/Installing+FusionReactor+in+Locked+Down+Environments.md': 'Admin-and-data/Licensing/Troubleshooting.md'
         'fr/help/Troubleshooting+Installation+Issues.md': 'index.md'
         'fr/help/ISAPI+and+FusionReactor.md': 'index.md'
         'fr/help/Installing+FusionReactor+in+Secured+Environments.md': 'index.md'
         'fr/help/Using+a+License+stored+in+the+Instance+Configuration+File.md': 'Admin-and-data/Licensing/Licensing.md'
         'fr/help/Licensing.md': 'Admin-and-data/Licensing/Licensing.md'
         'website/Home.md': 'index.md'
         'website/Quick+Start+to+Troubleshooting+Server+Problems+with+FusionReactor.md': 'index.md'
         'website/Protection+and+Monitoring+with+FusionReactor.md': 'index.md'

         'website/Migrating+FusionReactor+License+Key+to+another+server.md': 'index.md'
         'website/Archive+Distributions.md': 'index.md'
         'website/AWS+Elastic+Beanstalk.md': 'index.md'
         'website/OpenShift+Online.md': 'index.md'
         'website/Migrating+FusionReactor+to+a+new+server.md': 'index.md'
         'website/Migrating+FusionReactor+License+Key+to+another+server.md': 'index.md'
         'website/License+Types.md': 'Admin-and-data/Licensing/Licensing.md'
         'website/Applying+a+License+Key.md': 'Admin-and-data/Licensing/Licensing.md'
         'website/License+Activation.md': 'Admin-and-data/Licensing/Licensing.md'
         'website/License+Deactivation.md': 'Admin-and-data/Licensing/Licensing.md'
         'website/Licensing.md': 'Admin-and-data/Licensing/Licensing.md'
         'website/Using+a+License+stored+in+the+Instance+Configuration+File.md': 'Admin-and-data/Licensing/Licensing.md'
         'website/Completing+the+FRAM+install+-+bringing+instances+online.md': 'index.md'
         'website/License+Activation+(Manual).md': 'Admin-and-data/Licensing/Manual-Activation.md'
         'Cloud/Downloads/Downloads.md': 'Latest-updates/Downloads.md'
         'Cloud/OpenTelemetry/Instrumenting-OTel.md': 'Monitor-your-data/OpenTelemetry/getting-started.md'
         'Getting-started/Releases/#distributed-tracing.md': 'Monitor-your-data/OpenTelemetry/Visualize/Distributed-tracing.md'
         'Cloud/OpenTelemetry/Instrumenting-OTel.md': 'Monitor-your-data/OpenTelemetry/getting-started.md'
         'Cloud/guides/explore.md': 'Data-insights/Features/explore.md'
         'Cloud/guides/create-dashboard.md': 'Getting-started/Tutorials/create-dashboard.md'
         'Cloud/guides/OpsPilot/OpsPilot-user-guide.md': 'Data-insights/Features/OpsPilot/OpsPilot-user-guide.md'
         'Cloud/legal/licenses.md': 'Admin-and-data/Third-Party-Licenses/licenses.md'
         'licensing.md': 'Admin-and-data/Licensing/Licensing.md'
         'Cloud/billing/overview.md': 'Admin-and-data/Billing/Cloud/overview.md'
         'Cloud/guides/OpsPilot/OpsPilot-Hub/Jira.md': 'Data-insights/Features/OpsPilot/OpsPilot-Hub/Jira.md'
         'Cloud/guides/OpsPilot/OpsPilot-Hub/Knowledge.md': 'Data-insights/Features/OpsPilot/OpsPilot-Hub/Knowledge.md'
         'Cloud/guides/OpsPilot/OpsPilot-Hub/Slack.md': 'Data-insights/Features/OpsPilot/OpsPilot-Hub/Slack.md'
         'Cloud/guides/OpsPilot/OpsPilot-Hub/Teams.md': 'Data-insights/Features/OpsPilot/OpsPilot-Hub/Teams.md'
         'Cloud/OpenTelemetry/distributed-tracing.md': 'Monitor-your-data/OpenTelemetry/Visualize/Distributed-tracing.md'
         'Getting-started/Releases.md': 'Latest-updates/Releases.md'
         'Getting-started/WhatsNew.md': 'Latest-updates/WhatsNew.md'
         'deep.md': 'Monitor-your-data/Deep/overview.md'
         'release-notes.md': 'Latest-updates/release-notes.md'
         'Getting-started/DVCloud.md' : 'index.md'
         'OP-billing/licenses.md' : 'Admin-and-data/Billing/Cloud/overview.md'
         
           
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html


extra_css:
  - stylesheets/extra.css

extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

extra_javascript:
  - javascripts/feedback.js
  - 'https://code.jquery.com/jquery-3.4.1.min.js'
  - 'script/custom.js'
  - 'script/intercom.js'

copyright: '<a href="https://intergral.com" target="_blank">Copyright © 2026 Intergral GmbH. All rights reserved.</a>'
